build:
  environment:
    php: 7.3
  nodes:
    analysis:
      cache:
        directories:
          - vendor/
      tests:
        override:
          - command: bin/phpspec run --config=phpspec.yml
            coverage:
              file: coverage.xml
              format: clover
