build:
  environment:
    php: 7.3
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
          - command: bin/phpspec run --config=phpspec.yml
            coverage:
              file: coverage.xml
              format: clover
