name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update package manager
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install php7.3-bcmath php7.3-cli php7.3-curl php7.3-mbstring php7.3-xml -y        
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install composer
        run: wget https://getcomposer.org/composer.phar
      - name: Install composer packages
        run: php composer.phar install
      - name: Run tests
        run: bin/phpspec run
